name: screw-dev
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: development
    environment:
      - ENV=dev
      - IR_PATH=/app/audio/ir.wav
    env_file:
      - ./.env
    volumes:
      - ./api:/app
      - data:/app/data

  nextjs:
    build:
      context: ./nextjs
      dockerfile: Dockerfile
      target: development
    env_file:
      - ./.env
    volumes:
      - ./nextjs:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development

  proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "8080:80"
    depends_on:
      - api
      - nextjs
      - grafana
      - prometheus
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    restart: always

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:8080/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_LOG_LEVEL=warn
      - GF_LOG_MODE=console
      - GF_METRICS_ENABLED=false
volumes:
  data:
  grafana_data:
