name: screw

services:
  api:
    image: ghcr.io/mateopresacastro/screw/api:latest
    platform: linux/amd64
    environment:
      - ENV=prod
      - IR_PATH=/app/audio/ir.wav
    env_file:
      - ./api/.env
    volumes:
      - data:/app/data
    restart: always

  nextjs:
    image: ghcr.io/mateopresacastro/screw/nextjs:latest
    platform: linux/amd64
    restart: always

  proxy:
    image: ghcr.io/mateopresacastro/screw/proxy:latest
    platform: linux/amd64
    ports:
      - "80:80"
    restart: always

volumes:
  data:
