name: screw

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - ENV=prod
      - IR_PATH=/app/audio/ir.wav
    env_file:
      - ./api/.env
    volumes:
      - data:/app/data
    restart: always
  nextjs:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    restart: always
  proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always

volumes:
  data:
