name: screw-dev
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: development
    environment:
      - ENV=dev
      - IR_PATH=/app/audio/ir.wav
    env_file:
      - ./.env
    volumes:
      - ./api:/app
      - data:/app/data
    ports:
      - "3000:3000"

  nextjs:
    build:
      context: ./nextjs
      dockerfile: Dockerfile
      target: development
    env_file:
      - ./.env
    volumes:
      - ./nextjs:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development

  proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    restart: always

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  data:
  grafana_data:
