name: screw
services:
  api:
    image: ghcr.io/mateopresacastro/screw/api:latest
    platform: linux/amd64
    environment:
      - ENV=prod
      - IR_PATH=/app/audio/ir.wav
    env_file:
      - /home/ec2-user/app/api/.env
    volumes:
      - data:/app/data
    restart: always

  nextjs:
    image: ghcr.io/mateopresacastro/screw/nextjs:latest
    platform: linux/amd64
    restart: always

  proxy:
    image: ghcr.io/mateopresacastro/screw/proxy:latest
    platform: linux/amd64
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ec2-user/app/data/certbot/conf:/etc/letsencrypt:ro
      - /home/ec2-user/app/data/certbot/www:/var/www/certbot
    restart: always
    depends_on:
      - api
      - nextjs

  certbot:
    image: certbot/certbot
    volumes:
      - /home/ec2-user/app/data/certbot/conf:/etc/letsencrypt
      - /home/ec2-user/app/data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SERVER_ROOT_URL=/
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always
    depends_on:
      - prometheus

volumes:
  data:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
